### ISSUE TITLE
Mettre mon nom en arc-en-ciel

### ISSUE THREAD

**Issue by x-yzt** [x-yzt/psychonaut#1]
:> svp

**Comment by Tridimensionnel** [comment]
huhu, on a fait un point biquette et un thème dark sandmani, on peut bien faire un rôle "technicienne bipolaire" qui serait arc-en-ciel ? :3

**Comment by Snapyou2** [comment]
C'est fait en encore mieux qu'avant, j'espère que tu kiffes ^^

**Comment by x-yzt** [comment]
In-cro-yable

Mais ça fait beaucoup là non ?

Peut être quelque chose du genre :

```css
.username--style45 {
  --c1: rgb(42,222,240);
  --c2: rgb(131, 31, 244);

  color: transparent;
  background: linear-gradient(90deg, var(--c1), var(--c2), var(--c1), var(--c2));
  background-size: 300% 100%;
  background-clip: border-box;
  -webkit-background-clip: text;
  font-weight: bold;
  animation: gradient 5s linear infinite;
}

@keyframes gradient {
  from {
    background-position-x: 0%;
  }

  to {
    background-position-x: 100%;
  }
}
```

💜
